### ISSUE TITLE
Debian version not properly checked

### ISSUE THREAD

**Issue by eto-** [legend-exp/legendexp_legend-base_img#6]
since debian has version above 9 in install-sw.sh lines 27 and 29  should be `Debian GNU/Linux \([0-9]+\).*$')`

**Comment by oschulz** [comment]
Wanna make a PR?

**Comment by eto-** [comment]
No need it is a trivial change

**Comment by oschulz** [comment]
It should actually be `Debian GNU/Linux \([0-9]\+\).*$')`, I think.

I'll include it in the next container build.

**Comment by gipert** [comment]
Fixed in https://github.com/legend-exp/legendexp_legend-base_img/commit/4fbdfa253e8826762bd0afd0f426d9f271c65f5d.
